const $ = (selector) => document.querySelector(selector);

export const dom = {
  appShell: document.querySelector('.app-shell'),
  binInfo: $('#binInfo'),
  mainArea: document.querySelector('.main-area'),
  previewArea: document.querySelector('.preview-area'),
  controlCard: $('#controlCard'),
  controlToggle: $('#controlCardToggle'),
  controlRestore: $('#controlCardRestore'),
  previewExpand: $('#previewExpand'),
  portInput: $('#port'),
  portView: $('#portView'),
  applyMsg: $('#applyMsg'),
  cookiesView: $('#cookiesView'),
  log: $('#ytLog'),
  dlProg: $('#dlProg'),
  dlTxt: $('#dlTxt'),
  video: $('#localVideo'),
  videoFile: $('#videoFile'),
  pickVideo: $('#pickVideo'),
  useRemoteTimelineToggle: $('#useRemoteTimelineToggle'),
  remoteHud: $('#remoteHud'),
  remoteHudTitle: $('#remoteHudTitle'),
  remoteHudSubtitle: $('#remoteHudSubtitle'),
  remoteHudStatus: $('#remoteHudStatus'),
  remoteHudCurrent: $('#remoteHudCurrent'),
  remoteHudDuration: $('#remoteHudDuration'),
  remoteHudProgressFill: $('#remoteHudProgressFill'),
  ytUrl: $('#ytUrl'),
  fontsPicked: $('#fontsPicked'),
  pickCookies: $('#pickCookies'),
  clearCookies: $('#clearCookies'),
  checkBins: $('#checkBins'),
  pickSubs: $('#pickSubs'),
  pickFonts: $('#pickFonts'),
  clearFonts: $('#clearFonts'),
  forceDefaultFontToggle: $('#forceDefaultFontToggle'),
  ytDownload: $('#ytDownload'),
  ytDownloadAudio: $('#ytDownloadAudio'),
  ytCancel: $('#ytCancel'),
  ytFetch: $('#ytFetch'),
  background: $('#background'),
  align: $('#align'),
  maxWidth: $('#maxWidth'),
  maxHeight: $('#maxHeight'),
  subtitleOffsetToggle: $('#subtitleOffsetToggle'),
  subtitleOffsetSeconds: $('#subtitleOffsetSeconds'),
  applyToOverlay: $('#applyToOverlay'),
  clearOverlay: $('#clearOverlay'),
  activeCacheInfo: $('#activeCacheInfo'),
  toggleAdvanced: $('#toggleAdvanced'),
  closeAdvanced: $('#closeAdvanced'),
  advancedSidebar: $('#advancedSidebar'),
  sidebarOverlay: $('#sidebarOverlay'),
  binProgressWrap: $('#binProgressWrap'),
  binProgressBar: $('#binProgressBar'),
  binProgressLabel: $('#binProgressLabel'),
  binStatusYt: $('#binStatusYtIcon'),
  binStatusFfmpeg: $('#binStatusFfmpegIcon')
};

export { $ };
