export const state = {
  currentAssText: '',
  currentFonts: [],
  forceDefaultFont: true,
  defaultFontFamily: 'NotoSans-Regular',
  jobId: null,
  activeDownloadMode: null,
  cachedEntries: [],
  activeVideoId: '',
  activeSubsId: '',
  videoSearch: '',
  subsSearch: '',
  remoteSessions: [],
  remoteSelectedKey: '',
  remoteActiveSessionKey: '',
  objectUrl: '',
  binProgress: new Map(),
  binInfoRefreshTimer: null,
  controlCollapsed: false,
  previewMaximized: false,
  downloadProgressStarted: false,
  downloadStatusMessage: '',
  playerVolume: 1,
  useRemoteTimeline: false,
  remoteNowPlaying: null,
  remoteLastGuid: '',
  remoteLastUpdate: 0,
  remoteMediaKey: '',
  remoteProgressTimer: null,
  remoteCoverObjectUrl: '',
  remoteCoverSource: '',
  remoteCoverAbort: null,
  remoteCoverToken: 0,
  subtitleOffsetMode: 'advance',
  subtitleOffsetSeconds: 0,
  subtitleOffsetDefaults: { mode: 'advance', seconds: 0 },
  subtitleOffsetOverrides: {},
  overlayRefreshSeq: 0
};

export default state;
